rc.d file advance

diff --git a/tools/rc.d/yabh b/tools/rc.d/yabh
--- a/tools/rc.d/yabh
+++ b/tools/rc.d/yabh
@@ -17,28 +17,32 @@ run_yabh() {
 }
 
 yabh_start() {
-    debug "Check for configuration at ${yabh_configuration_path}"
-    if [ ! -f "${yabh_configuration_path}" ] ; then
-        err 1 "${yabh_configuration_path} no such file"
+    if checkyesno ${rcvar} ; then
+        debug "Check for configuration at ${yabh_configuration_path}"
+        if [ ! -f "${yabh_configuration_path}" ] ; then
+            err 1 "${yabh_configuration_path} no such file"
+        fi
+        debug "Check for executable at ${yabh_exe}"
+        if [ ! -f "${yabh_exe}" ] ; then
+            err 1 "${yabh_exe} no such file"
+        fi
+        if [ ! -x "${yabh_exe}" ] ; then
+            err 1 "${yabh_exe} is not set as executable"
+        fi
+        debug "Check configuration file ${yabh_configuration_path}"
+        run_yabh check
+        if [ $? -ne 0 ] ; then
+            err 1 "yabh check has failed"
+        fi
+        debug "Start jails"
+        run_yabh jail jail start
     fi
-    debug "Check for executable at ${yabh_exe}"
-    if [ ! -f "${yabh_exe}" ] ; then
-        err 1 "${yabh_exe} no such file"
-    fi
-    if [ ! -x "${yabh_exe}" ] ; then
-        err 1 "${yabh_exe} is not set as executable"
-    fi
-    debug "Check configuration file ${yabh_configuration_path}"
-    run_yabh check
-    if [ $? -ne 0 ] ; then
-        err 1 "yabh check has failed"
-    fi
-    debug "Start jails"
-    run_yabh jail jail start
 }
 yabh_stop() {
-    debug "Stop jails"
-    run_yabh jail jail stop
+    if checkyesno ${rcvar} ; then
+        debug "Stop jails"
+        run_yabh jail jail stop
+    fi
 }
 
 load_rc_config $name
